# This setting allows you to disable the askyblock hook even if you have askyblock on the server.
# If you simply want to disable flight in the askyblock world use the disabled worlds
# setting in the base plugin.
enable_hook: true
# The feature unlockables allows you to set island requirements to allow users
# flight on islands and elsewhere on the server.
# Island level is the minimum level the players island must be to 
# fly in the area. Challenges is a list of challenges that must be completed
# to fly in the area.
unlockables:
  # Requirements needed for island members to fly in specified regions
  regions:
    super_awesome_vip_region:
      island_level: 950
      challenges:
        - 'alchemist'
        - 'dj'
        - 'beaconator'
  # Requirements needed for island members to fly in specified worlds
  worlds:
    example_world:
      island_level: 1
      challenges:
        - ''
  # requirements to fly when not on an island.
  wilderness:
    island_level: 0
    challenges:
      - ''
  # requirements needed for the island owner to fly on the island
  owner:
    island_level: 1
    challenges:
      - ''
  # Requirements needed for team members to fly on the island
  team:
    island_level: 5
    challenges:
      - 'breadmaker'
  # Requirements needed for coop players to fly on the island
  coop:
    island_level: 15
    challenges:
      - 'papermaker'
  # Requirements needed for visitors to fly on the island
  visitor:
    island_level: 25
    challenges:
      - 'stewmaker'
      
flight_settings:
  # If false the player cannot fly when they are not on an island
  wilderness: true
  base_permissions:
    # The following settings are the default values for the tempfly's island protection panel
    # Island owners may allow or disallow players flight on their island. Changing these values
    # WILL NOT effect islands that have already established their settings.
    
    # Team members can fly on the island
    team: true
    # Coop players can fly on the island
    coop: true
    # Visitors can fly on the island
    visitor: false

language:
  invalid:
    island: "{PREFIX} &cYou must have an island to fly here!"

  requirements:
    challenge: "{PREFIX} &cYou must complete the challenge &f{CHALLENGE} &cto fly here!"
    level_self: "{PREFIX} &cYou must have an island level of &f{LEVEL} &cto fly here!"
    level_other: "{PREFIX} &cThis island does not meet the level requirement for &f{STATUS}'s &cto fly!"
