##--------------------------------------------------------------------------------------##
#|                                                                                      |#
#|                ,--------.                       ,------.,--.                         |# 
#|                '--.  .--',---. ,--,--,--. ,---. |  .---'|  |,--. ,--.                |# 
#|                   |  |  | .-. :|        || .-. ||  `--, |  | \  '  /                 |# 
#|                   |  |  \   --.|  |  |  || '-' '|  |`   |  |  \   '                  |# 
#|                   `--'   `----'`--`--`--'|  |-' `--'    `--'.-'  /                   |# 
#|                                          `--'               `---'                    |#
#|               ,----.      ,--.      ,-----.  ,------.,--------. ,---.                |#
#|               '.-.  |    /    \     |  |) /_ |  .---''--.  .--'/  O  \               |#
#|                 .' <    |  ()  |    |  .-.  \|  `--,    |  |  |  .-.  |              |#
#|               /'-'  |.--.\    /     |  '--' /|  `---.   |  |  |  | |  |              |#
#|               `----' '--' `--'      `------' `------'   `--'  `--' `--'              |#
#|                                                                                      |#
#|                                      Beta  #2                                        |#
#|                                                                                      |#
##--------------------------------------------------------------------------------------##
#|                                                                                      |#
#|                                       Author                                         |#
#|                                  =---=------=---=                                    |#
#|                                   ChiefMoneyBags                                     |#
#|                                                                                      |#
##--------------------------------------------------------------------------------------##
#|                                                                                      |#
#|                            <--Commands & Permissions-->                              |#
#|                                                                                      |#
#|    https://github.com/ChiefMoneyBags/TempFly/blob/Master/TempFly/permissions.yml     |#
#|                                                                                      |#
##--------------------------------------------------------------------------------------##

system:
  # Time in minutes to backup data
  backup: 5
  # If true your console will be subjected to spam from the internal workings of the plugin.
  # If you have an issue i may ask you to turn it on.
  debug: false
  # Connect to an sql database for storage.
  # This will disable yaml data storage.

  # DO NOT ENABLE SQL IT IS NOT READY IN THIS BETA VERSION, It wont save your data.
  sql:
    enabled: false
    host: "127.0.0.1"
    port: "0000"
    user: "user"
    pass: "pass"

general:
  # This feature prevents conflictions with other plugins fly features.
  # By default tempfly will steal priority and take the command /fly away from other plugins.
  # If the player has a permission listed below tempfly will not override the command /fly for them.
  fly_override_permissions:
    - 'essentials.fly'
  
  disabled:
    worlds:
      - 'example_world'
    regions:
      - 'test'
  
  timer:
    # If true the players timer will count down no matter what as long as they are on the server.
    # If you want the time to count down while they are offline please see the feature "time_decay"
    constant: false
    # If false the player will not lose flight time if standing on the ground with flight enabled.
    ground: false
    # If false the player will not lose flight time if they go idle with flight enabled.
    idle: false
  
  idle:
    # The threshold in seconds to consider a player idle. -1 for no idle timer
    threshold: 300
    # If true players tempfly will be disabled if they go idle in the sky (dropping them).
    drop_player: false

  flight:
    # Set the default maximum speed players can fly unless otherwise specified by the tempfly.speed.[speed] permission.
    # This does not automatically set the speed to this number unless it is less than 1, it specifies their default maximum allowed speed.
    default_speed: 1
    # The maximum y level a player can reach before flight is disabled.
    maximum_height: 275
  
  time:
    # If true players can send eachother time as if it were a currency.
    payable: true
    # The maximum time in seconds a player is allowed to have. -1 for no limit.
    # The permission is "tempfly.max.{group}"
    # For one global max you can just do-
    # max_time: {time}
    max_time:
      member: -1
      vip: -1
  
  bonus:
    # Time in seconds given to a player when they first join the server.
    first_join: 10
    # Permission based time given to a player as a daily login bonus.
    # The permission is "tempfly.bonus.{group}"
    # Time will stack for each permission the player inherits. Make sure to configure your permissions properly.
    daily_login: 
      member: 10
      vip: 30

    
  time_decay:
    # If enabled a player will lose time when logged off the server.
    # info:
    # - This will not track every offline player, it only updates when the player rejoins the server. no lags.
    # - To use this in tandem with the constant_timer, set threshold and seconds_lost both to 1. (1 second lost per 1 second offline).
    enabled: false
    # The interval in which players will lose time (seconds)
    threshold: 3600
    # Seconds of flight lost per interval
    seconds_lost: 15

  # If true, flight is disabled when the player;
  combat:
    # ...attacks another player
    attack_player: true
    # ...attacks a mob
    attack_mob: false
    # ...is attacked by a player
    attacked_by_player: true
    # ...is attacked by a mob
    attacked_by_mob: false

    # Seconds before flight can be enabled after pvp 
    pvp_tag: 10
    # Seconds before flight can be enabled after pve 
    pve_tag: 5
  
  # If false the player will not take fall damage when flight is disabled;
  damage:
    # ...by command
    on_command: false
    # ...by running out of time
    out_of_time: true
    # ...from combat
    combat: true
    # ...from going idle
    idle: false
    # ...from entering a disabled world
    world: false
      # ...from entering a disabled region
    region: false

aesthetic:
  # Features that allow you to easily see if a player is flying using tempfly.
  identifier:

    tab_list:
      # If enabled, the players name on tab will change to this when they are in tempflight.
      enabled: true
      # Valid placeholers: {PLAYER} The players name | {OLD_TAG} The origional name on tab, including prefixes.
      # Supports placeholders for time
      name: "&d~{OLD_TAG}"

    name_tag:
      # If enabled, the players name tag will change to this when they are in tempflight.
      # (Not currently compatible with plugin "essentials")
      enabled: true
      # Valid placeholers: {PLAYER} The players name | {OLD_TAG} The origional name tag, including prefixes.
      # Supports placeholders for time      
      name: "&d~{OLD_TAG}"

    particles:
      # If false all trails are disabled.
      enabled: true
      # The default particle type.
      type: 'VILLAGER_HAPPY'
      # If true all players will have the default particle trail enabled by default.
      display_by_default: true
      # If true particles will not be displayed if the player is vanished.
      # Tested with plugins SuperVanish, PremiumVanish, VanishNoPacket.
      hide_vanish: true

  # Title to warn players of remaining flight time
  warning:
    # valid placeholders {SECONDS} {MINUTES} {HOURS} {DAYS}
    title: "&cWARNING!"
    subtitle: "&fYou have &c{SECONDS} &fseconds of flight remaining!"
    # Time intervals in seconds to display the title to players.
    # ONLY use numbers
    seconds:
      - 30
      - 15
      - 5

  action_bar:
    enabled: true
    text: "&6Flight meter&7: {FORMATTED_TIME}"

# Oddball features and things many people probably wont use can be found here.
other:
  # relative time is a feature that lets you control how fast time will be used in worlds and regions.
  # this can be useful for many things, for example, making time move slower on larger planets on a space themed server due to higher gravity
  # In the example below;
  # - time will pass '0.5' times or 50% slower than in real time on world 'example_world'
  # - time will pass '1.5' times or 50% faster than in real time in region 'example_region'.
  # If the player is in both 'example_world' and 'example_region' at once the values will
  # be factored together resulting in a value of 0.75 or 25% slower.
  relative_time:
    worlds:
      example_world: 0.5
    regions:
      example_region: 1.5
    
# Quality of life feature for servers that dont want to implement a whole shop gui plugin, but just want a simple tempfly shop.
shop:
  general:
    # If false the built in shop will not exist.
    enabled: false
  # You can add as many options with any name you want
  options:
    five_mins:
      # The time to give the player in seconds
      time: 300
      # The cost of the time, any vault currency is supported
      cost: 7500
    thirty_mins:
      time: 1800
      cost: 30000
    one_hour:
      time: 3600
      cost: 50000
      
        