name: TempFly
main: moneybags.tempfly.TempFly
softdepend: [ASkyBlock, Essentials, MVdWPlaceholderAPI, PlaceholderAPI, aSkyBlock, Vault, WorldGuard, WorldEdit]
api-version: 1.13
version: 3.0.0
commands:
    tempfly:
        description: base command
        aliases: [tfly, tf]