# This setting allows you to disable the skyblock hook even if you have skyblock on the server.
# If you just want to disable flight in the island worlds use disabled worlds in the base config.
enable_hook: true

# Unlockables allow you to set island requirements to allow users flight on islands and elsewhere on the server.
# Island level is the minimum level the players island must be to fly in the area.
# Challenges are a list of challenges that must be completed to fly in the area.
unlockables:

  environment:
    # Requirements needed for island members to fly in specified regions
    region:
      super_awesome_vip_region:
        island_level: 950
        challenges:
          - 'alchemist'
          - 'dj'
          - 'beaconator'
  
    # Requirements needed for island members to fly in specified worlds
    world:
      example_world:
        island_level: 1
        challenges:
          - ''
  
    # requirements to fly when not on an island.
    wilderness:
      island_level: 0
      challenges:
        - ''

  # Below are flight requirements based on island roles.
  # Valid requirements include;
  # island_level: the island level for the player trying to fly.
  # owner_level: the island level for the island they are trying to fly on.
  # challenges: the challenges for the player trying to fly.
  # owner_challenges: the challenges for the owner of the island they are trying to fly on.

  # If the role specified is a member of the island, for example, (team, moderator, owner) there
  # is no need to specify both island_level and owner_level as they will be the same thing.
  island_roles:
    owner:
      island_level: 5
      challenges:
        - ''

    visitor:
      island_level: 75
      owner_level: 50

      challenges:
        - 'stewmaker'
      owner_challenges:
        - 'papermaker'

flight_settings:
  # If false the player cannot fly when they are not on an island
  wilderness: true

  # The following settings are the default values for the tempfly's island protection panel
  # Island owners may allow or disallow island roles flight on their island.
  base_permissions:
    # Team members can fly on the island
    team: true
    # Coop players can fly on the island
    coop: true
    # Visitors can fly on the island
    visitor: false

language:
  invalid:
    island: "{PREFIX} &cYou must have an island to fly here!"

  requirements:
    owner_challenge: "{PREFIX} &cThis island has not unlocked flight for &f{ROLE}&c's!"
    challenge: "{PREFIX} &cYou must complete the challenge &f{CHALLENGE} &cto fly here!"
    island_level: "{PREFIX} &cYou must have an island level of &f{LEVEL} &cto fly here!"
    owner_level: "{PREFIX} &cThis island does not meet the level requirement for &f{ROLE}'s &cto fly!"

gui:
  # EXPERIMENTAL
  # This setting will allow you to place a button inside the island settings panel for your respective
  # skyblock plugin that will take the user to the tempfly island settings page.
  hook_settings:
    enabled: true
    button:
      name: "&dTemp&fFly &fIsland Settings"
  page:
    settings:
      title: "&dIsland Flight Settings"
      background:
        name: "&7- Please select an option"
      toolbar:
        name: "&7- Please select an option"
      role:
        name: "&e&l{ROLE}"
        lore:
          - "&8&m================"
          - "&7- Set whether team {ROLE}'s can fly"
