name: TempFly
main: com.moneybags.tempfly.TempFly
softdepend: [ASkyBlock, Essentials, MVdWPlaceholderAPI, PlaceholderAPI, aSkyBlock, Vault, WorldGuard, WorldEdit, IridiumSkyblock, BentoBox]
api-version: 1.13
version: 3.1.2
commands:
    tempfly:
        description: base command
        aliases: [tfly, tf]